name: Main Push
on:
  push:
    branches:
      - "Structure-test"
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: yarn release

      - name: Publish
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
